
-- AlterTable
ALTER TABLE "Setting" ADD COLUMN "companyName" TEXT NOT NULL DEFAULT 'DIP ENTERPRISE';
ALTER TABLE "Setting" ADD COLUMN "legalName" TEXT NOT NULL DEFAULT 'DIP Enterprise Cloud';
ALTER TABLE "Setting" ADD COLUMN "address" TEXT NOT NULL DEFAULT 'Bongaon, West Bengal, India';
ALTER TABLE "Setting" ADD COLUMN "phone" TEXT NOT NULL DEFAULT '+91 90000 00000';
ALTER TABLE "Setting" ADD COLUMN "email" TEXT NOT NULL DEFAULT 'dipenterprise.bongaon.de@gmail.com';
ALTER TABLE "Setting" ADD COLUMN "gstin" TEXT NOT NULL DEFAULT '19DIPEN1234A1Z5';
ALTER TABLE "Setting" ADD COLUMN "logoUrl" TEXT NOT NULL DEFAULT '/logo.png';
ALTER TABLE "Setting" ADD COLUMN "bankName" TEXT NOT NULL DEFAULT 'State Bank of India';
ALTER TABLE "Setting" ADD COLUMN "accountNo" TEXT NOT NULL DEFAULT 'XXXXXX4521';
ALTER TABLE "Setting" ADD COLUMN "ifsc" TEXT NOT NULL DEFAULT 'SBIN0001234';
ALTER TABLE "Setting" ADD COLUMN "bankBranch" TEXT NOT NULL DEFAULT 'Bongaon';
ALTER TABLE "Setting" ADD COLUMN "upi" TEXT NOT NULL DEFAULT 'dipenterprise@upi';
